// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfmgwmcqepzuonkhqfit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmbWd3bWNxZXB6dW9ua2hxZml0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3MzI0ODUsImV4cCI6MjA4NDMwODQ4NX0.o4YZWks_ejVxME8k6VcoRQCRG6ZNBlR2GIv9iwpsBUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});